### ISSUE TITLE
FR: auto restart service

### ISSUE THREAD

**Issue by Frenzie** [gabm/TapAndTurn#40] opened 2017-08-29 10:33 UTC
c4b42d0b5bdd55542fdb551d4cb7342c1ecb3213 disables the service completely if the app is temporarily locked out of drawing overlays due to installing or updating an app, or granting permissions.

Also see https://github.com/gabm/TapAndTurn/issues/39#issuecomment-325598649

**Comment by gabm** [comment] 2017-08-29 10:41
I re-checked .. i don't think that this is the case for installing/uninstalling or updating apps?! that should work in any case without taking away the permissions?!

**Comment by gabm** [comment] 2017-08-29 10:47
Currently I have the feeling that its quite sensible to auto-deactivate TnT and force the user through the re-activation process. The problem is the missing user-interface, actually just disabling TnT as long as the permission is not granted would work technically, but there is no real way of comunicating to the user: "Hey, please give the permission back".. 

Options that come to my mind are:
1. displaying a toast on every rotation attempt saying: "I'm not showing u the TnT button, because I can't, please give me the permission back!"
2. silently do nothing and query for permission on every rotation attempt and when we have the permission back, return to normal operation 
3. When permission-loss is detected, switch off TnT completly and force the user through the main menu

Do you have other options? what do you suggest?

**Comment by Frenzie** [comment] 2017-08-29 10:47
I made a quick video on my Zenfone 2 with Android 6 to demonstrate (remove the .zip extension; it's just a video).

[VID_20170829_124434.mp4.zip](https://github.com/gabm/TapAndTurn/files/1259988/VID_20170829_124434.mp4.zip)

**Comment by gabm** [comment] 2017-08-29 10:50
ok, thats indeed different on Android 6.. I see...though I'm worried about user interaction.. what would you suggest? @Frenzie 

@licaon-kter what is your opinion?

**Comment by licaon-kter** [comment] 2017-08-29 10:51
Toast is fine.

**Comment by Frenzie** [comment] 2017-08-29 10:55
I think a combination of options would be the most user-friendly if it's not too much trouble to implement. 

Silently query for permission until you hit some arbitrary limit (e.g., `20` total tries, or exceeded `30s` since first failed attempt), then display a toast.

**Comment by gabm** [comment] 2017-08-29 10:56
ok.. I'll have a look into the code and let you know...

**Comment by Frenzie** [comment] 2017-08-29 10:58
Awesome, thanks! Btw, which version of Android did you test with?

**Comment by gabm** [comment] 2017-08-29 10:59
I'm always on the latest.. 7.1.2 i think - It seems this permission/overlay thing changed a lot between 6 and 7 ..

**Comment by gabm** [comment] 2017-09-01 08:32
Ok, I checked and it looks good to me, I'll release it soon, but it will be a bit delayed due to another feature...

**Comment by Frenzie** [comment] 2017-09-01 09:34
No problem. Thanks for the quick response!

**Comment by gabm** [comment] 2017-09-04 06:42
that should be released with 2.8.0 .. may take a while till it lands in fdroid..

**Closed as completed by gabm** 2017-09-04 06:42 UTC
