### ISSUE TITLE
Crash when draw-over permission not granted

### ISSUE THREAD

**Issue by licaon-kter** [gabm/TapAndTurn#39] opened 2017-08-17 11:58 UTC
Steps:
* have the app installed
* install some other app
* grant that app some permissions ( #38 )
* forget that you've toggle OFF the "draw over other app" permission for TapAndTurn
* see TapAndTurn crash repeatedly ( [logcat](https://gist.github.com/licaon-kter/fd7f5a7602cc7b49490cd8e03bbc01ab) ) until said permission is granted back

The app needs to cope with the fact that the permission is missing, maybe sprinkle some `try{}` here or there. :)

**Comment by gabm** [comment] 2017-08-17 14:54
indeed.. there is something wrong ;) I'll have a look...

**Comment by gabm** [comment] 2017-08-17 15:24
That should be fixed in next version - TnT switches itself off when it notices that the permission got lost meanwhile...

**Comment by gabm** [comment] 2017-08-18 07:34
this has been released as 2.7.0

**Closed as completed by gabm** 2017-08-18 07:34 UTC

**Comment by Frenzie** [comment] 2017-08-29 08:50
Would there be a sensible manner to try to auto re-enable?

**Comment by licaon-kter** [comment] 2017-08-29 09:00
Apps can't "auto-grant" themselves permissions...

**Comment by Frenzie** [comment] 2017-08-29 09:18
Who's talking about auto-granting? The service quits running because it is *temporarily* locked out.

**Comment by gabm** [comment] 2017-08-29 09:40
i think the but discussed here is solved on 2.7.. please either reopen this issue or create a new one...

**Comment by Frenzie** [comment] 2017-08-29 10:30
Right, I'm talking about the behavior caused by the fix in c4b42d0b5bdd55542fdb551d4cb7342c1ecb3213.

**Comment by gabm** [comment] 2017-08-29 10:33
ok, I'll try to guess what u mean:

you are talking about the behavior "when the permission gets lost, then tnt switches itself off"? and you want tnt to auto-reactivate when it gets the permission back?
